### ISSUE TITLE
Some issues with jnc scripts

### ISSUE THREAD

**Issue by Miracutor** [Nosgoroth/wepub#1]
1. Can't run the scripts at first
This is caused by an incorrect reference to BeautifulSoup in wepubutils.py. Solved by changing BeautifulSoup to bs4 inline 15
`from bs4 import BeautifulSoup,Tag`

2. Can't generate configs.
I tried using check function to generate configs but only show errors. I also tried to generate volume and series but also failed.

3. Can't detect user-created configs
Because of the documentation is only given the example of wepubdl version of config, I tried to copy config exactly in documentation and tried to run it but only give me errors. I also tried to convert that guided by example in configs folder but also errors.

**Comment by Nosgoroth** [comment]
Hi,

Please try to install the latest release of BeautifulSoup from the 3.x branch (3.2.2 right now, although I have 3.2.1), not the 4.x branch, and see if those errors go away. If they don't, I'm going to need more details to be able to do anything meaningful about them.

I'll update the docs to reflect the BS version thing.

**Comment by Miracutor** [comment]
I changed to that version and... it works! Thanks for your fast reply!
